In [1]:
from nltk import ngrams

In [2]:
sentence = "I love Natural language processing"
tokens = sentence.split()
bigrams = list(ngrams(tokens, 2))
print(bigrams)

[('I', 'love'), ('love', 'Natural'), ('Natural', 'language'), ('language', 'processing')]


In [3]:
## 7 bag of words

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
corpus = [
    "I love the camera quality.",
    "The battery life is too short",
    "Amazing phone with great features",
    "Screen size too small"
]

In [6]:
vectorizer = CountVectorizer()

In [7]:
X_bow = vectorizer.fit_transform(corpus)

In [9]:
print("BoW Feature Names:", vectorizer.get_feature_names_out())
print("BoW Matrix: \n", X_bow.toarray())

BoW Feature Names: ['amazing' 'battery' 'camera' 'features' 'great' 'is' 'life' 'love'
 'phone' 'quality' 'screen' 'short' 'size' 'small' 'the' 'too' 'with']
BoW Matrix: 
 [[0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0]
 [1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0]]


In [10]:
# tfidf

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tfidf = TfidfVectorizer()

In [13]:
X_tfidf = tfidf.fit_transform(corpus)
print("TF-IDF Feature Names:", tfidf.get_feature_names_out())
print("TF-IDF Matrix:", X_tfidf.toarray())

TF-IDF Feature Names: ['amazing' 'battery' 'camera' 'features' 'great' 'is' 'life' 'love'
 'phone' 'quality' 'screen' 'short' 'size' 'small' 'the' 'too' 'with']
TF-IDF Matrix: [[0.         0.         0.52547275 0.         0.         0.
  0.         0.52547275 0.         0.52547275 0.         0.
  0.         0.         0.41428875 0.         0.        ]
 [0.         0.43671931 0.         0.         0.         0.43671931
  0.43671931 0.         0.         0.         0.         0.43671931
  0.         0.         0.34431452 0.34431452 0.        ]
 [0.4472136  0.         0.         0.4472136  0.4472136  0.
  0.         0.         0.4472136  0.         0.         0.
  0.         0.         0.         0.         0.4472136 ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.52547275 0.
  0.52547275 0.52547275 0.         0.41428875 0.        ]]


In [14]:
#Sentiment analysis

In [15]:
reviews = [
    "I love this product! It's amazing and works perfectly.",
    "Worst experience ever. It broke after one use.",
    "Not bad, but could be better.",
    "Excellent quality and fast delivery.",
    "Terrible! Waste of money."
]
labels = [1,0,1,1,0]

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


In [18]:
tfidf = TfidfVectorizer()

In [21]:
X = tfidf.fit_transform(reviews)
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

In [22]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [1]:
#POS

In [5]:
import nltk

# Correct resource names
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

sentence = "The quick brown fox jumps over the lazy dog."

# Tokenize the sentence
tokens = nltk.word_tokenize(sentence)

# Get POS tags
pos_tags = nltk.pos_tag(tokens)

# Print the result
print("POS Tags:", pos_tags)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shahu\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\shahu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger_eng')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger_eng/

  Searched in:
    - 'C:\\Users\\shahu/nltk_data'
    - 'D:\\Anaconda\\nltk_data'
    - 'D:\\Anaconda\\share\\nltk_data'
    - 'D:\\Anaconda\\lib\\nltk_data'
    - 'C:\\Users\\shahu\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [7]:
grammar = "NP: {<DT>?<JJ>*<NN>}"

chunk_parser = nltk.RegexParser(grammar)
tree = chunk_parser.parse(pos_tags)

print("Noun Phrase Chunks:")
for subtree in tree.subtrees(filter=lambda t: t.label() == 'NP'):
    print(" ".join(Word for word, tag in subtree.leaves()))

AttributeError: module 'nltk' has no attribute 'RegexParser'

In [8]:
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp("The quick brown fox jumps over the lazy dog.")

print("Depnedency Parse:")
for token in doc:
    print(f"{token.text:<10} {token.dep_:<10} --> {token.head.text}")

ModuleNotFoundError: No module named 'spacy'